config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :albums
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "albums#index"
end

app/models/album.rb
class Album < ApplicationRecord
    has_one_attached :cover_image
    has_many_attached :photos, dependent: :destroy 

    validates :cover_image, presence: true
    validates :photos, presence: true 
    validates :title, presence: true, length: { maximum: 255 }
    validates :description, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
    
    has_many :taggings
    has_many :tags, through: :taggings

def all_tags=(names)

    self.tags = names.split(",").map do |name|
        Tag.where(name: name.strip).first_or_create!
    end
  end
  
  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.ransackable_associations(auth_object = nil)
    ["tags"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "price", "title", "updated_at"]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :albums, through: :taggings


    def self.ransackable_attributes(auth_object = nil)
        [
          "name"
        ]
      end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :album
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,  only: %i[ create  edit update destroy ]

  # GET /albums or /albums.json
  def index
      @q = Album.ransack(params[:q])
      @albums = @q.result(distinct: true)
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit    
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    
    respond_to do |format|
      if @album.update!(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album = Album.find(params[:id])

    @album.taggings.destroy_all
    
    @album.destroy
  
    # Destroy associated rich text content
    
    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_description }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :description, :price, :all_tags, :cover_image, photos: [])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.erb
<div id="<%= dom_id(album) %>" class="container mt-4">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title text-center mb-4">
        Album Details: <%= album.title %>
      </h4>

      <div class="row">
        <div class="col-md-6">
          <strong>Cover Photo:</strong>
          <div class="mb-3">
            <%= image_tag(album.cover_image, alt: "Album Cover", class:
            'img-fluid rounded') %>
          </div>
        </div>

        <div class="col-md-6">
          <strong>Photos:</strong>
          <% if album.photos.attached? %>
          <div class="row">
            <% album.photos.each do |photo| %>
            <div class="col-6 col-lg-4 mb-3">
              <%= image_tag(photo, class: 'img-fluid rounded') %>
            </div>
            <% end %>
          </div>
          <% else %>
          <p>No photos available.</p>
          <% end %>
        </div>
      </div>

      <hr />

      <div class="row">
        <div class="col-md-6">
          <strong>Description:</strong>
          <p><%= album.description %></p>
        </div>

        <div class="col-md-6">
          <div class="row">
            <div class="col-6">
              <strong>Tag:</strong>
              <p><%= album.all_tags %></p>
            </div>
            <div class="col-6">
              <strong>Price:</strong>
              <p><%= album.price %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/albums/_form.html.erb
<%= form_with(model: album, class: 'mt-4') do |form| %>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <% if album.errors.any? %>
          <div class="alert alert-danger">
            <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

            <ul>
              <% album.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :cover_image, 'Upload Album Cover Image', class: 'form-label' %>
          <div class="input-group">
            <div class="custom-file">
              <%= form.file_field :cover_image, class: 'custom-file-input', id: 'cover-image' %>
              <label class="custom-file-label" for="cover-image"></label>
            </div>
          </div>
        </div>

        <div class="mb-3">
          <% if album.cover_image.attached? %>
            <div class="uploaded-image-box text-center" style: "height:80%;width:100%">
              <%= image_tag album.cover_image, class: 'img-fluid rounded' %>
            </div>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :photos, 'Upload Album Photos', class: 'form-label' %>
          <%= form.file_field :photos, multiple: true, class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="mb-3">
          <%= form.label :title, 'Album Title', class: 'form-label' %>
          <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :description, 'Album Description', class: 'form-label' %>
          <%= form.text_area :description, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :all_tags, 'Tags', class: 'form-label' %>
          <%= form.text_field :all_tags, placeholder: "Enter tags separated by commas", class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :price, 'Album Price', class: 'form-label' %>
          <%= form.number_field :price, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="mb-3 text-center">
      <%= form.submit 'Save Album', class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<style>
  .album-actions {
    display: flex;
    justify-content: space-around;
    margin-top: 20px;
  }

  .action-button, .action-button-danger {
    padding: 10px 20px;
    font-size: 16px;
    text-align: center;
    text-decoration: none;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .action-button {
    background-color: #4CAF50; /* Green */
    color: white;
  }

  .action-button:hover {
    background-color: #45a049; /* Darker green on hover */
  }

  .action-button-danger {
    background-color: #f44336; /* Red */
    color: white;
  }

  .action-button-danger:hover {
    background-color: #d32f2f; /* Darker red on hover */
  }
</style>

<div class="album-actions mb-5">
  <%= button_to "Show this album", @album, method: :get, class: "action-button" %>
  <%= button_to "Back to Albums", albums_path, method: :get, class: "action-button" %>
</div>

app/views/albums/index.html.erb
<div class="container mt-5">

  <%= search_form_for @q, html: { class: 'mb-4' } do |f| %>
    <div class="input-group">
      <%= f.label :tags_name_cont, "Tag:", class: 'input-group-text' %>
      <%= f.search_field :tags_name_cont, class: 'form-control' %>
      <button class="btn btn-primary" type="submit">Search</button>
    </div>
  <% end %>

  <h1 class="my-4">Albums</h1>

  <div class="row">
    <% @albums.each do |album| %>
      <div class="col-lg-3 mb-4">
        <div class="card h-100">
        <strong>Cover Photo:</strong>
        <div class="mb-3 w-100">
          <%= image_tag(album.cover_image, alt: "Album Cover", class: 'img-fluid rounded') %>
        </div>
          <div class="card-body">
            <h5 class="card-title">Title: <%= album.title %></h5>
            <p class="card-text">Description: <%= album.description %></p>
            <p class="card-text">Tag: <%= album.all_tags %></p>
            <p class="card-text">Price: <%= album.price %></p>
          </div>
          <div class="card-footer">
            <div class="btn-group" role="group" aria-label="Actions">
              <%= link_to 'Show', album, class: 'btn btn-primary' %>
              <%= link_to 'Edit', edit_album_path(album), class: 'btn btn-secondary' %>
              <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class=" mb-5">
  <%= link_to 'New Album', new_album_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>

<br>

<style>
  .album-actions {
    display: flex;
    justify-content: space-around;
    margin-top: 20px;
  }

  .action-button, .action-button-danger {
    padding: 10px 20px;
    font-size: 16px;
    text-align: center;
    text-decoration: none;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .action-button {
    background-color: #4CAF50; 
    color: white;
  }

  .action-button:hover {
    background-color: #45a049; 
  }

  .action-button-danger {
    background-color: #f44336; 
    color: white;
  }

  .action-button-danger:hover {
    background-color: #d32f2f;
  }
</style>

<div class="album-actions mb-5">
  <%= button_to "Back to albums", albums_path, method: :get, class: "action-button" %>
</div>

app/views/albums/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @album %>

<style>
  .album-actions {
    display: flex;
    justify-content: space-around;
    margin-top: 20px;
  }

  .action-button, .action-button-danger {
    padding: 10px 20px;
    font-size: 16px;
    text-align: center;
    text-decoration: none;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .action-button {
    background-color: #4CAF50; /* Green */
    color: white;
  }

  .action-button:hover {
    background-color: #45a049; /* Darker green on hover */
  }

  .action-button-danger {
    background-color: #f44336; /* Red */
    color: white;
  }

  .action-button-danger:hover {
    background-color: #d32f2f; /* Darker red on hover */
  }
</style>

<div class="album-actions mb-5">
  <%= button_to "Edit", edit_album_path(@album), method: :get, class: "action-button" %>
  <%= button_to "Back to Albums", albums_path, method: :get, class: "action-button" %>
  <%= button_to "Destroy", @album, method: :delete, data: { confirm: "Are you sure?" }, class: "action-button-danger" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GalleryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" 
    crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
        
  <%= render 'shared/header' %>

    <%= yield %>
    
  <%= render 'shared/footer' %>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" 
    crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<style>
    body {
        background-color: #f8f9fa; /* Light gray background color */
        color: #495057; /* Dark text color */
        font-family: 'Arial', sans-serif; /* Choose a suitable font */
    }

    .footer {
        background-color: #343a40; /* Dark background color for the footer */
        color: #ffffff; /* Light text color for the footer */
        padding: 40px 0; /* Add some padding to the footer */
    }

    .footer h2 {
        color: #ffc107; /* Yellow text color for the footer headings */
    }

    .footer p,
    .footer a {
        opacity: 0.8; /* Slightly reduce the opacity of text in the footer */
    }

    .footer a:hover {
        opacity: 1; /* Full opacity on hover for links in the footer */
    }

    .contact-address span {
        display: inline-block;
        margin-bottom: 8px; /* Slightly increase the margin */
    }

    .copy {
        background-color: #343a40; /* Dark background color for the copyright section */
        color: #ffffff; /* Light text color for the copyright text */
        padding: 10px 0; /* Add some padding to the copyright section */
    }

    .copy p {
        margin: 0; /* Remove default margin for the copyright text */
    }
</style>



<body>
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4  mt-4">
                    <h2>About Us</h2>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor repellendus iure impedit vitae
                        perferendis ab odit illo adipisci, quia ut assumenda deserunt laboriosam. Animi, inventore?</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aliquam ducimus quaerat
                        repellat amet Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, iste et rem quae
                        libero ad assumenda distinctio esse facilis, repellat nesciunt exercitationem veritatis illum
                        quo? Quae optio, repudiandae. </p>
                </div>
                <div class="col-lg-4  mt-4">
                    <h2>Useful Links</h2>
                    <ul>
                        <li><a href="#About_us">About us</a></li>
                        <li><a href="#Portfolio">Portfolio</a></li>
                        <li><a href="#jobs">Latest jobs</a></li>
                        <li><a href="#Gallery">Gallery</a></li>
                        <li><a href="#Contact_us">Contact Us</a></li>
                    </ul>
                </div>
              <div class="col-lg-4  mt-4">
                <h2>Contact Us</h2>
                <div class="contact-address">
                    <span>Sector 60</span>
                    <span>Mohali</span>
                    <span>Punjab, IND</span>
                    <span>Phone: +91 9087654321</span>
                    <span>Email: <a href="mailto:sample@xyz.com">sample@xyz.com</a></span>
                    <span>Web: <a href="#" target="_blank">www.sample.in</a></span>
                </div>
            </div>
            </div>
        </div>
    </footer>

    <div class="copy">
        <div class="container">
            <p>&copy; 2023 All Rights Reserved | Designed and Developed by DS Atul</p>
        </div>
    </div>

</body>

</html>

app/views/shared/_header.html.erb
<style>
  .navbar {
    position: sticky;
    top: 0;
    background: linear-gradient(to right, #3498db, #2c3e50);
    z-index: 1;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  }

  .navbar-brand {
    color: #fff;
    font-size: 24px;
    font-weight: bold;
  }

  .navbar-nav {
    margin-left: auto;
  }

  .nav-link {
    color: #fff;
    margin: 0 15px;
    font-size: 16px;
    transition: color 0.3s;
  }

  .nav-link:hover {
    color: #ffd700; 
  }

  .user-info, .user-actions, .guest-actions {
    color: #fff;
  }

  .btn {
    margin-right: 10px;
  }

  .dropdown-menu {
    background-color: #3498db;
    color: #fff;
  }

  .dropdown-menu a {
    color: #fff;
  }
</style>




<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <%= link_to "Gallery", root_path, class: "nav-link active" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">price</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Stores</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
              <% if user_signed_in? %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Logged in as <%= current_user.email %>
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="userDropdown">
                    <li><%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %></li>
                    <li><%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, method: :delete, class: 'dropdown-item' %></li>
                  </ul>
                </li>
              <% else %>
                <div class="guest-actions">
                  <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success' %>
                  <%= link_to "Login", new_user_session_path, class: 'btn btn-primary' %>
                </div>
              <% end %>
            </li>
          </ul>
        </form>
      </div>
    </div>
</nav>